version: "2"
run:
  tests: true
linters:
  enable:
    - dupl
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - revive
    - unconvert
  settings:
    dupl:
      threshold: 100
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      enable:
        - shadow
formatters:
  enable:
    - gofmt
    - goimports
issues:
  exclude-generated: lax
  exclude-dirs:
    - vendor
    - examples
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
    - linters:
        - revive
      text: "should have comment or be unexported"
    - linters:
        - revive
      text: "stutters"