run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - gosec
    - ineffassign
    - misspell
    - unconvert
    - gocritic
    - gocyclo
    - gosimple
    - staticcheck
    - unused
    - typecheck
    - errcheck
    - dupl
    - goimports
    - revive

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-dirs:
    - vendor
    - examples
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
    - linters:
        - revive
      text: "should have comment or be unexported"
    - linters:
        - revive
      text: "stutters"