run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - examples

linters:
  enable:
    - gofmt
    - golint
    - govet
    - gosec
    - ineffassign
    - misspell
    - unconvert
    - gocritic
    - gocyclo
    - gosimple
    - staticcheck
    - unused
    - deadcode
    - typecheck
    - errcheck
    - structcheck
    - varcheck
    - dupl
    - goimports

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
    - linters:
        - golint
      text: "should have comment or be unexported"